### ISSUE TITLE
Not compatible with new symfony components

### ISSUE THREAD

**Issue by rudirocha** [wata727/pahout#17]
Hi.
Actually the package cannot be installed with symfony components for version 4 of symfony.
Do you have any plans to continue the package?

> $ composer require --dev wata727/pahout
> Using version ^0.2.0 for wata727/pahout
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for wata727/pahout ^0.2.0 -> satisfiable by wata727/pahout[0.2.0].
>     - wata727/pahout 0.2.0 requires symfony/console ^3.3 -> satisfiable by symfony/console[3.3.x-dev, 3.4.x-dev, v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3, v3.4.0-BETA4, v3.4.0-RC1, v3.4.0-RC2, v3.4.1, v3.4.2] but these conflict with your requirements or minimum-stability.
> 
> 
> Installation failed, reverting ./composer.json to its original content.

cheers

**Comment by wata727** [comment]
@rudirocha Good catch! I'm going to focus on this project :)

I would like to support compatibility for multiple versions of Symfony components, as in the example below:
https://github.com/phan/phan/blob/0.11.0/composer.json#L27

Perhaps I will fix it to work with version 3 and version 4.

Thanks!

**Comment by rudirocha** [comment]
there should not be any major differences between 3.4 and 4.0 for symfony so I would say that you could just update composer to set as requirement ">=3.3" for instance.
When do you think you will release a new version?

Thanks

**Comment by wata727** [comment]
Thanks for the advice.
I'm taking a little time to solve dependency now. However, I plan to release it as soon as possible.

**Comment by wata727** [comment]
@rudirocha I've been released Pahout v0.3.0 ! Please try it and give me feedback :)

**Comment by rudirocha** [comment]
Indeed tested and working.
Thanks for your effort :) validations being done!

Cheers
