### ISSUE TITLE
pahout cannot run on development versions of PHP

### ISSUE THREAD

**Issue by fisharebest** [wata727/pahout#48]
I'm using pahout as part of my continuous integration testing using travis-ci.

I'm using the `nightly` PHP version, which is currently `7.4.0-dev`.

The final `-dev` in the version number causes pahout to fail because of these lines:
https://github.com/wata727/pahout/blob/0.4.0/src/Config.php#L160-L165

I realise that I can create a file `.php-version` to override this:
https://github.com/wata727/pahout/blob/0.4.0/src/Config.php#L68-L71

However, it means that I need to write a script to parse the current PHP version, remove the stability indicator and create `.php-version` before I can run pahout.

IMHO, it would be better if pahout simply ignored the stability indicator of the current version.

Here's a simple way to do it.

```
php > echo explode('-', '7.4.0-dev')[0];
7.4.0
php > echo explode('-', '7.4.0')[0];
7.4.0
```

**Comment by wata727** [comment]
Good catch. Thanks for your report.
Probably, we should follow [`version_compare`'s way](https://secure.php.net/manual/en/function.version-compare.php) to parse PHP-standardized version.
